spring:
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/contacts}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
server:
  port: 3030

phoneValidationApikey: ${PV_API_KEY:ef2509e2bd186c36b25af4622eabcce3}
emailValidationApikey: ${EV_API_KEY:a4f424ba295049aea2de064f2fb6fb3f}
