spring:
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/contacts}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 3030

#Reseted api keys which both has around 95 calls left
phoneValidationApikey: ${PV_API_KEY:314eaaf5f7e04bbcd770f81597cf7ee1}
emailValidationApikey: ${EV_API_KEY:9d00d0f5fb1e4a1785cfa59a89127809}
